DWAPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.3
  max_vel_y: 0.3
  min_vel_y: -0.3
  max_vel_theta: 0.5
  min_vel_theta: -0.5

  acc_lim_x: 0.1
  acc_lim_y: 0.1
  acc_lim_theta: 0.1

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.1
  stop_time_buffer: 0.2

  holonomic_robot: true
  scaling_speed: 0.25
  max_scaling_factor: 0.2
