local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  transform_tolerance: 1.0
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.05

  plugins:  # Указываем используемые плагины
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:  # Настройки слоя препятствий
    observation_sources: scan
    scan:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      max_obstacle_height: 0.5

  inflation_layer:  # Настройки инфляционного слоя
    inflation_radius: 0.1